### PR TITLE
Port libcamera changes for renaming sdl_texture_yuyv.{cpp,h} to sdl_t…

### PR DESCRIPTION
**Pull request by sdunnagan**
This is a merge request for porting libcamera changes to twincam,
for renaming sdl_texture_yuyv.{cpp,h} to sdl_texture_yuv.{cpp,h}.

### CODE REVIEW

**Comment by ericcurtin** [comment]
For this change, what would you think about creating new sdl_texture_nv12.h/sdl_texture_nv12.cpp files? I know libcamera changed the name of these files from sdl_texture_yuvv to sdl_texture_yuv to group yuyv and nv12 pixel formats together, but I'd rather keep one class per file if possible.

Or the libcamera way is ok too, I guess, I prefer one class per file.

Either way I think it's worth sticking the nv12 changes into this PR.

**Comment by sdunnagan** [comment]
Hey Eric,

Yep, makes sense!  I created separate files for nv12 changes and ported
these two libcamera commits:
cam: sdl_sink: Add NV12 texture support
<https://github.com/kbingham/libcamera/commit/7b8df9fe6b3eedc46667d07ad2c90c89ca823e0c>
cam: sdl_sink: Support multi-planar formats
<https://github.com/kbingham/libcamera/commit/d4a42894b158f5f248ca94a8331bb8a40e051e3c>

I'm not sure how to test the NV12 stuff, but I made sure the camera works
on x86_64 (Fedora 36).

I'll create a new PR for this.

Thanks,

Steve
:)

**Comment by ericcurtin** [comment]
I have an NV12 camera, I'll try and find time to test it... I'm actually happy to merge as many new formats as possible even if I can't test them, as long as they are separated out into separate code paths where they can't break existing functionality.

**Comment by kbingham** [comment]
If you merge in the vivid branch, and modprobe vivid you'll get a virtual camera that pretty much generates any format.

https://git.libcamera.org/libcamera/vivid.git/log/

I think there's an option to make vivid use the DMA contiguous allocator which is needed to get the frames direct to Kms though, but it might be helpful for testing other formats.

**Comment by ericcurtin** [comment]
Thanks @kbingham , @Yarboa is always asking about this area in general, could be useful for CI. Have fun in Dublin by the way if you are going, I'm disappointed I won't make it with it being so close. Had a couple of clashing appointments.

**Pull request closed without merging**
